services:
  voca:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - DECIDIM_VERSION=0.29.4
      - PORT=3000
      - MAPS_PROVIDER=osm
      - MAPS_STATIC_PROVIDER=osm
      - MAPS_STATIC_URL=https://a.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png
      - MAPS_STATIC_API_KEY=my_insecure_api_key
      - MAPS_DYNAMIC_PROVIDER=osm
      - MAPS_DYNAMIC_URL=https://a.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}@2x.png
      - MAPS_DYNAMIC_API_KEY=my_insecure_api_key
      - MAPS_GEOCODING_HOST=nominatim.openstreetmap.org
      - MAPS_ATTRIBUTION=<a href="https://www.openstreetmap.org/copyright" target="_blank">Â© OpenStreetMap</a> contributors
      - DATABASE_URL=postgis://decidim:pleaseChangeMe@voca-pg:5432/decidim
      - DATABASE_HOST=voca-pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DISABLE_SPRING=1
      - DEV_MODULE=decidim-voca
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE=true # To run tests in dockeril vole de building en build
      - DECIDIM_DEEPL_API_KEY=my_deepl_api_key
      - RACK_ATTACK_BLOCK_SYSTEM=false
      - MASTER_ID=voca
      - MASTER_IP=voca
      - TRAEFIK_REDIS_URL=redis://traefik-db:6379/1
      - TRAEFIK_SERVICE_PROTOCOL=http
      - TRAEFIK_SERVICE_PORT=3000
      - TRAEFIK_CERT_RESOLVER=selfsigned
      - TRAEFIK_SERVICE_HEALTHCHECK_INTERVAL=10s
      - TRAEFIK_SERVICE_HEALTHCHECK_TIMEOUT=10s
    depends_on:
      - voca-pg
    ports:
      - 3000:3000
    links:
      - voca-pg
      - traefik-db

  traefik-db:
    image: redis:8.4.0
    restart: always
    volumes:
      - traefik-db-data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli -h localhost -p 6379 ping
      interval: 5s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:3.6.2
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./.docker:/etc/traefik
    depends_on:
      - traefik-db
    links:
      - voca
    environment:
      - DEBUG=1
      - TRAEFIK_DEBUG=1
      - TRAEFIK_LOG_LEVEL=DEBUG

  voca-pg:
    image: postgis/postgis:16-3.5-alpine
    restart: always
    volumes:
      - voca-pg-data:/var/lib/postgresql/data
      - .docker/dump:/tmp/dump
    environment:
      - POSTGRES_PASSWORD=pleaseChangeMe
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U decidim -h 127.0.0.1
      interval: 5s

volumes:
  node_modules: {}
  bundle: {}
  voca-pg-data: {}
  traefik-db-data: {}